### ISSUE TITLE
Basic Readme for reproducibility

### ISSUE THREAD

**Issue by remo-help** [gelato-org/gelato-data#12]
Hi, my colleagues and I read the PNAS paper and we would like to utilize your database/ reproduce your results.

Do you have a short readme on how to run your scripts (or rather, which ones to run) and how to run the database itself (or where to find it in your codebase)?

Best
Remo

**Comment by xrotwang** [comment]
The dataset is here: https://github.com/gelato-org/gelato-data/tree/v1.0/cldf - it's a [CLDF StructureDataset](https://cldf.clld.org), i.e. the summary statistics are modeled as "parameters" with "values" measured for "languages".

**Comment by xrotwang** [comment]
The code for the analyses in the paper is here: https://github.com/gelato-org/MatchesMismatches

**Comment by remo-help** [comment]
Thanks, I can figure it out from here!
